### PR TITLE
Structure view enhancement

### PR DESCRIPTION
**Pull request by mqualizz**
Improve handling of closures
* as assignment values
* as function call arguments

### CODE REVIEW

**Comment by mqualizz** [comment]
Please note -- I didn't know how to label closures, so currently they are labeled as "<anonymous> (...)" (where "..." denotes the actual arg list).  Please let me know if you want this handled in a different way.

**Comment by tangzx** [comment]
Great ! Can you add some tests here? https://github.com/EmmyLua/IntelliJ-EmmyLua/blob/master/src/test/kotlin/com/tang/intellij/test/structure/StructureViewTest.kt

**Comment by mqualizz** [comment]
Sure thing!

**Comment by mqualizz** [comment]
I hate to sound like a n00b, but I can't figure out how to run the tests.  Any hints?

**Comment by tangzx** [comment]
Open `StructureViewTest.kt`, Did you see this button?
image
Just click it.

**Comment by mqualizz** [comment]
Sorry for not being clear.  I was talking about the exceptions raised while trying to run the tests -- what does your run/debug configuration look like for a test?

/Library/Java/Home/bin/java -ea "-Xbootclasspath/a:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/boot.jar" -Didea.load.plugins.id=com.tang -Didea.home.path=/Users/mqualizz/Library/Caches/IntelliJIdea2017.3/plugins-sandbox/test -Didea.plugins.path=/Users/mqualizz/Library/Caches/IntelliJIdea2017.3/plugins-sandbox/plugins -Didea.test.cyclic.buffer.size=104857600 -Didea.launcher.port=56936 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/junit/lib/junit-rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/junit/lib/junit5-rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/aether-1.1.0-all.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/aether-dependency-resolver.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/alloy.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/annotations.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/asm-5.0.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/asm-all.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/asm-analysis-5.0.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/asm-tree-5.0.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/automaton.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/batik-all.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/bcprov-jdk15on-155.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/boot.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/cglib-nodep-3.2.4.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/cli-parser-1.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/clojure-1.8.0.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/clojure-jsr223-1.5.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/cloud-config-client.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/common-image-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/common-io-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/common-lang-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/commons-codec-1.9.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/commons-compress-1.10.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/commons-httpclient-3.1-patched.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/commons-logging-1.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/commons-net-3.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/constraint-layout.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/coverage-agent.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/coverage-instrumenter.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/coverage-util.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/ecj-4.6.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/external-system-rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/fluent-hc-4.5.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/forms_rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/google-analytics-library.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/groovy-all-2.4.12.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/guava-21.0.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/hamcrest-core-1.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/httpclient-4.5.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/httpcore-4.4.5.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/httpmime-4.5.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/icons.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/idea-jsp-openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/idea.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/ideax.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/imageio-core-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/imageio-metadata-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/imageio-tiff-3.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/imgscalr-lib-4.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/ini4j-0.5.2-patched.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/isorelax.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jasper21_rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jasper2_rt.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/javac2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jaxen-1.1.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jayatana-1.2.4.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jcip-annotations.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jdkAnnotations.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jediterm-pty-2.5.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jettison-1.3.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jgoodies-common-1.2.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jgoodies-forms.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jgoodies-looks-2.4.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jh.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jimfs-1.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jing.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jna-platform.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jna.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jps-builders-6.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jps-builders.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jps-launcher.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jps-model.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch-0.1.54.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.connector-factory.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.core.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.jsch.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.pageant.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.sshagent.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.usocket-jna.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsch.agentproxy.usocket-nc.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jshell-frontend.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jshell-protocol.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsp-api.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jsr173_1.0_api.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/junit-4.12.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/jzlib-1.1.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/kotlin-reflect.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/kotlin-runtime.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/markdown4j-2.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/markdownj-core-0.4.2-SNAPSHOT.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/maven-aether-provider-3.3.9-all.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/microba.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/miglayout-core-5.0.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/miglayout-swing-5.0.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/nanoxml-2.2.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/nekohtml-1.9.14.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/netty-all-4.1.13.Final.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/optimizedFileManager.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/oromatcher.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/picocontainer.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/proxy-vole-1.0.3.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/pty4j-0.7.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/purejavacomm.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/resolver.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/resources.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/resources_en.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/rhino-js-1_7R4.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/rngom-20051226-patched.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/serviceMessages.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/servlet-api.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/slf4j-api-1.7.10.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/slf4j-log4j12-1.7.10.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/snakeyaml-1.17.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/snappy-in-java-0.5.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/sqlite-jdbc-3.16.1.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/studio-profiler-grpc-1.0-jarjar.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/swingx-core-1.6.2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/trang-core.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/trilead-ssh2.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/velocity.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/wadl-core.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/winp-1.23.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xbean.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xercesImpl.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xml-apis-ext.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xmlgraphics-commons-1.5.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xmlrpc-2.0.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xpp3-1.1.4-min.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xstream-1.4.8.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/xz-1.5.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/lib/yjp-controller-api-redist.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/gradle-javaee.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/IntelliLang-javaee.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/javaee-jps-plugin.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/javaee-openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/resources_en.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/JavaEE/lib/webDeployment-transport.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/PersistenceSupport/lib/persistence-openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/PersistenceSupport/lib/resources_en.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/DatabaseTools/lib/database-openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/DatabaseTools/lib/resources_en.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/DatabaseTools/lib/unidecode-0.0.7.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/CSS/lib/css-openapi.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/CSS/lib/resources_en.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/uml/lib/diagram-api.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/Spring/lib/spring-aop.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/Spring/lib/spring-api.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/Spring/lib/spring-eclipse.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/Spring/lib/spring-graph.jar:/Applications/IntelliJ IDEA 2017.3 EAP.app/Contents/plugins/Spring/lib/spring-web.jar:/Library/Java/Home/jre/lib/charsets.jar:/Library/Java/Home/jre/lib/deploy.jar:/Library/Java/Home/jre/lib/ext/cldrdata.jar:/Library/Java/Home/jre/lib/ext/dnsns.jar:/Library/Java/Home/jre/lib/ext/jaccess.jar:/Library/Java/Home/jre/lib/ext/jfxrt.jar:/Library/Java/Home/jre/lib/ext/localedata.jar:/Library/Java/Home/jre/lib/ext/nashorn.jar:/Library/Java/Home/jre/lib/ext/sunec.jar:/Library/Java/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/Home/jre/lib/ext/zipfs.jar:/Library/Java/Home/jre/lib/javaws.jar:/Library/Java/Home/jre/lib/jce.jar:/Library/Java/Home/jre/lib/jfr.jar:/Library/Java/Home/jre/lib/jfxswt.jar:/Library/Java/Home/jre/lib/jsse.jar:/Library/Java/Home/jre/lib/management-agent.jar:/Library/Java/Home/jre/lib/plugin.jar:/Library/Java/Home/jre/lib/resources.jar:/Library/Java/Home/jre/lib/rt.jar:/Library/Java/Home/lib/ant-javafx.jar:/Library/Java/Home/lib/dt.jar:/Library/Java/Home/lib/javafx-mx.jar:/Library/Java/Home/lib/jconsole.jar:/Library/Java/Home/lib/packager.jar:/Library/Java/Home/lib/sa-jdi.jar:/Library/Java/Home/lib/tools.jar:/Users/mqualizz/GIT/IntelliJ-EmmyLua/out/test/IntelliJ-EmmyLua:/Users/mqualizz/GIT/IntelliJ-EmmyLua/out/production/IntelliJ-EmmyLua:/Users/mqualizz/GIT/IntelliJ-EmmyLua/libs/markdown.jar:/Users/mqualizz/GIT/IntelliJ-EmmyLua/libs/luaj-jse-3.0.1.jar" com.intellij.rt.execution.application.AppMainV2 com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit3 com.tang.intellij.test.structure.StructureViewTest,testLocalVariable
log4j:WARN No appenders could be found for logger (#com.intellij.util.ui.JBUI).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider org.intellij.images.util.imageio.CommonsImagingImageReaderSpi could not be instantiated

	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at org.intellij.images.fileTypes.impl.ImageFileTypeManagerImpl.createFileTypes(ImageFileTypeManagerImpl.java:69)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:294)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:254)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:452)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:456)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:54)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:46)
	at com.intellij.testFramework.LightPlatformTestCase.initApplication(LightPlatformTestCase.java:169)
	at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:50)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.g(CodeInsightTestFixtureImpl.java:1194)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:58)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1193)
	at com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.setUp(LightPlatformCodeInsightFixtureTestCase.java:38)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:380)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$2.run(EdtTestUtil.kt:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/imaging/ImageReadException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 54 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.imaging.ImageReadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 59 more


Process finished with exit code 255

**Comment by tangzx** [comment]
Sorry, but I haven't seen this before.
Here's my configuration (Test all)
image

**Pull request merged**
