### PR TITLE
Type casting support

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Support for type casting, and block-style doc quotes.

The combination of which facilitates code like:

```lua
---@param returnString boolean
---@return string|number
function stringOrNumber(returnString)
    return returnString and "someString" or 1
end

---@param n number
function wantsNumber(n)
end

wantsNumber(stringOrNumber(false)) -- Raises type error (or at least, it should. Fix in #323)
wantsNumber(--[[---@type number]] stringOrNumber(false))

wantsNumber(
    ---@type number @Single line doc comments work too
    stringOrNumber(false)
)
```

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
I still need to sort out a test.

Basically:

```lua
---@module TypeA
module("TypeA")
```

is being interpreted as a type-cast, rather than a module definition. Inserting a blank line between the two would fix the test/issue, however it's probably best not to break backward compatibility even if `module` is deprecated.

**Comment by tangzx** [comment]
Thank you @Benjamin-Dobell
But `Lua -> Lint -> Type safety` just an experimental feature, it has too many issues (disabled by default), I regret to say don't spend too much time on this until it's stable.

**Comment by Benjamin-Dobell** [comment]
@tangzx Just letting you know that I've done a huge amount of work on `Type Safety`. It should now function reliably and supports all sorts of additions:

- **Generic classes**
- Generics parameter constraints referencing other generic parameters
- Support for generic params in `@type` annotations in context's that make sense.
- Primitive literals
- Snippets
- Type casts
- `self` improvements
- Lots of inspection fixes
- Additional inspections

All in all it should close a lot of open issues.

Because it's such a substantial amount of changes I've written a heap of tests (28 files worth). _However_, I've run into a [bug with IntelliJ's test suite](https://youtrack.jetbrains.com/issue/IJSDK-799), so it may take me a little while to get that resolved.

Just though I better let you know 😄

**Comment by Benjamin-Dobell** [comment]
Closed in favour of https://github.com/EmmyLua/IntelliJ-EmmyLua/pull/342

**Pull request closed without merging**
