### PR TITLE
Generics, indexed fields, callable types, shapes, literals and more

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Firstly, I apologise for the size of this pull request, it's *massive*. Unfortunately I can't break this up into smaller feature commits as each feature tends to depend on (and extend or fix) prior features/commits.

# What's New

## Demo Project

The best way to see what's new is probably to checkout the [demo project](https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/)[1] I put together. If you open this project up in the existing version of EmmyLua (and enable Type Safety linting) you'll see a lot of new that stuff is simply unsupported in the current release. However, you'll also come across a few cases where EmmyLua does understand the EmmyDoc's but is still missing linting errors. 

_[1] This project is also packaged in this pull request as the basis for the tests (there are lots of new tests)._

### EmmyDoc Block Comments

Screen Shot 2020-03-30 at 4 10 12 pm

### Type casts

The `@type` tag can now we used to perform a cast when applied to a Lua expression. This is most useful with the newly added support for EmmyDoc block comments as we can easily specify inline type casts:

Screen Shot 2020-03-30 at 4 12 49 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/type_casts.lua

### Improved variance detection

Inspections were previously attempting to determine if a type was assignable to another type simply by checking if the former is a "subtype" of latter, however variance wasn't formerly specified. However, this only works in the simple case, take for example functions where variance is well defined for function parameters:

Screen Shot 2020-03-30 at 5 28 54 pm

The existing EmmyLua release does _not_ report the above error.

Additionally, union variance detection has been fixed:

Screen Shot 2020-03-30 at 5 37 08 pm

As above, the current release of EmmyLua does not catch this error.

### Primitive literal types

Screen Shot 2020-03-30 at 4 24 59 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/string_literals.lua

### Referencing of generic parameter types inside functions

Screen Shot 2020-03-30 at 4 27 46 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/function_generics_scope.lua

### Binding of EmmyDoc to lambdas in assignments

i.e. Type checking now works inside function "lambdas" assigned to a variable with an EmmyDoc definition.

Screen Shot 2020-03-30 at 4 29 56 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/lambda_params.lua

### Table type checking improvements

Various improvements, for example EmmyDoc "arrays" are now assignable to compatible table types e.g.

Screen Shot 2020-03-30 at 5 39 47 pm

The current EmmyLua release will report an error here even though this is sound.

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/tables.lua

### Generic classes (!!!)

Screen Shot 2020-03-30 at 5 41 58 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/generic_class_fields.lua

### Support for generic params referencing generic params

Screen Shot 2020-03-30 at 5 44 19 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/function_generics.lua#L226-L249

### Generic inference fixes

The current EmmyLua release is unable to infer generics correctly in several situations and thus reports type errors where no error exists, and also misses errors where errors should exist e.g.

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/function_generics.lua#L151-L178

### Type errors are now errors

By default, type safety errors are now reported as errors instead of warnings. This is made feasible by three things:

1. Many improvements in the ability to specify complex types
2. Type safety bug fixes
3. _Casting_

Casting in particular means that if a user is doing something the type system deems unsafe, but they know at runtime will be fine, they can just add a cast to signify this and the error will go away. 

### Generic parameter use _within a class_

Screen Shot 2020-03-30 at 5 57 19 pm

Shadowing of a generic parameter is forbidden and an error reports:

Screen Shot 2020-03-30 at 6 35 43 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/generic_class_scope.lua

### New "No such member" inspection

Screen Shot 2020-03-30 at 6 38 18 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/generic_class_fields.lua#L44-L45

### `self` is now a real type

Improved type checking for `self`, for example `self` can be assigned to a variable that matches the parent type of a method. However, that parent type cannot be assigned to `self`, as the class may be sub-classed (in which case `self` refers to a more specific type).

Screen Shot 2020-03-30 at 6 40 53 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/self.lua

### Assign type inspection now applies to variables assigned at variable declarations

Screen Shot 2020-03-30 at 6 44 09 pm

Current EmmyLua release will allow this invalid assignment.

### Fixed a bug where the type inference cache was being used in the presence of an index

When a function returns multiple values, the current EmmyLua release will infer values and put them in the cache. This is inaccurate as generic types analysis may result in the same generic parameter being resolved differently based on the value being assigned, thus the cache cannot be used in this circumstance. Presently this results in both missing errors, and additional inaccurate errors, depending on the assignment.

### Added support for `@shape` (!!!)

A shape can be defined similarly to a class, except that contravariance is determined by compatibility of the members _not_ the inheritance hierarchy.

This is most useful when working with "structures" (e.g. JSON) rather than OOP classes.

Screen Shot 2020-03-30 at 7 11 28 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/shape.lua

What makes shapes particularly useful is that they support generics and inheritance (at definition time, not assignment) just like classes:

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/shape.lua#L36-L74

Even _better_, type inspections are not just reported on incompatible `table`s as whole, but rather the inspections know how to traverse _table literals_ and provide detailed annotations of incompatibilities between two shapes e.g.

Screen Shot 2020-03-30 at 7 15 25 pm

### Generic Aliases (!!!)

Aliases can now take generic parameters, just like a class or shape.

Screen Shot 2020-03-30 at 7 19 18 pm

https://github.com/Benjamin-Dobell/EmmyLua-AdvancedTypesDemo/blob/master/src/generic_alias.lua

### Improved vararg syntax

Function types can now use `...: T` as an alternative to `vararg T`:

Screen Shot 2020-04-24 at 12 47 19 am

### Variadic return values (!!!)

We now support variadic return values:

Screen Shot 2020-04-24 at 12 31 44 am

Internally, `TyTuple` has been replaced with `TyMultipleResults` to reflect the fact that this construct is not fixed size. Additionally, multiple results are now properly handled in more locations.

### Standard library type improvements

Various improvements to typings of Lua built-ins taking advantage of variadic return values etc.

### Support for indexed fields (!!!)

We can now type all properties of tables, not just string constants. Given that this PR also adds support for primitive literal types we can use this a lot of different ways e.g.

Screen Shot 2020-04-24 at 2 10 26 am

Here we have regular string identifier fields, number literal fields `[1]`, `[2]` and `[3]` _and_ a `[boolean]` field. That last one is really powerful, because it's _not_ a constant, it's a real type.

We can type custom data structures e.g.

```lua
---@class Dictionary<K, V>
---@field [K] V
```

This will work correctly for any `K` and everything will be statically type checked as you'd expect.

There's also syntax for table types, it works for table literals _and_ anonymous classes (i.e. tables that aren't explicitly typed):

Screen Shot 2020-04-24 at 2 14 14 am

### Partially typed functions

We now support `fun` types with optional parameter lists and optional return values i.e. `fun: boolean` and `fun(arg: boolean)`. `fun` (with neither specified) also works for posterity but is functionally equivalent to the existing `function` type.

Partially typed functions are extremely useful for implementing callback and handler patterns. For example, it's quite common to have an extensible event system where each event has unique arguments, but the handler must return `true` to indicate the event was handled:

Screen Shot 2020-04-24 at 2 22 15 am

### Callable types (!!!)

This is another _really_ useful feature. We can now properly indicate that an object is callable (i.e. is a `table` whose metatable has a `__call` method).

Screen Shot 2020-04-24 at 2 25 48 am

This is done by using the existing `@overload` EmmyDoc keyword, and works similarly i.e. we can specify many overloads and type checking and completion will work as you'd expect:

Screen Shot 2020-04-24 at 2 27 57 am

# Tests

There are a [heap of new tests](https://github.com/Benjamin-Dobell/IntelliJ-EmmyLua/blob/type-safety/src/test/kotlin/com/tang/intellij/test/inspections/TypeSafetyTest.kt) to validate this new functionality. Unfortunately, a couple of these new tests have had to be disabled due to a bug in the IntelliJ Platform SDK (https://youtrack.jetbrains.com/issue/IDEA-234428). Nonetheless, the majority of the new functionality has running new tests. Additionally, all the new functionality can be manually verified by checking out the aforementioned demo project.

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
A debugging import (`import com.sun.xml.bind.v2.runtime.reflect.opt.Const`) was left in (hence the Appveyor failure). I've fixed the offending commit and force pushed - all passing now.

**Comment by tangzx** [comment]
Wow... 👍 thank you for this great pull request! As you said, it's massive, You've added a lot of new features. I need some time to review.

**Comment by Benjamin-Dobell** [comment]
Just pushed an additional commit the ensure empty table literals are interpreted as being covariant of all `table<T, T>` and `T[]`,

**Comment by Benjamin-Dobell** [comment]
I've rebased this PR on the upstream `type-safety` branch _and_ added some really useful additions, as well as some bug fixes (for generics, ignore snippets in type checking etc.)

The new features are documented in detail in the first post, but in summary they are:

* Improved vararg syntax
* Variadic return values (!!!)
* Standard library type improvements
* Support for indexed fields (!!!)
* Partially type functions
* Callable types (!!!)

There's been quite a bit of refactoring to make this all work, however these are incredibly useful features. You can now accurately define types for the vast majority of Lua constructs _and_ benefit from type checking with them.

**Comment by Benjamin-Dobell** [comment]
The test that Appveyor is reporting as failed is:

```
com.tang.intellij.test.refactoring.MoveFileTest > testMoveFile FAILED
    kotlin.TypeCastException at MoveFileTest.kt:32
```

which wasn't altered by this PR and was last changed October 18, 2017.

I've actually had trouble with this test failing locally from time to time as well.

To fix it, I just delete the cache and run the tests again and it works. I did actually look into it at one stage. If I recall correctly, it gets in a bad state resulting in failed attempts to access temporary files/directories i.e. a bug in Jetbrains Platform SDK and nothing todo with EmmyLua or this PR.

**Comment by adriweb** [comment]
Just wanted to drop by to thank you for your efforts, we use Lua and EmmyLua extensively at work and this will be really great!

**Comment by Benjamin-Dobell** [comment]
Not sure what's up with the CI. Perhaps using a corrupt build cache?

Anyway, last 2 commits were all bug fixes, and the one prior was a small type compatibility improvement.

**Comment by adriweb** [comment]
So hm, with this PR getting closed, is there any hope of having this officially integrated anymore or should people just use the fork?
And, will you rebase your fork against upstream/here if necessary?

**Comment by Benjamin-Dobell** [comment]
You can install my fork from https://plugins.jetbrains.com/plugin/14698-luanalysis.

It has quite a bit of additional stuff beyond what was included in this PR, and many bug fixes.

However, I'm still actively working on it (literally have commits that I'll be pushing in the next hour or so). If at some stage it were to be merged back into EmmyLua that'd be great, however for now what I'm doing is still somewhat experimental, I've made substantial changes internally, and I've every intention of making breaking changes in the near future (https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/issues). If this were to be merged now it'd actually be more difficult for me to continue active development.

Perhaps down the track if @tangzx is agreeable to it, it could be merged down the track as an EmmyLua 2.0 build or something like that.

**Comment by Benjamin-Dobell** [comment]
By the way, if anyone is looking for a real world project using all this stuff, you can take a look at:
https://github.com/Benjamin-Dobell/ge_tts

**Pull request closed without merging**
